# Generated by Django 4.0.5 on 2022-06-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='mostrar',
        ),
    ]
